# Generated by Django 3.1.3 on 2021-10-18 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Name')),
                ('player1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Player 1')),
                ('player2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Player 2')),
                ('player3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Player 6')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Password')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'All Teams',
            },
        ),
        migrations.CreateModel(
            name='TeamAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Token')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
            options={
                'verbose_name': 'Team Access Token',
                'verbose_name_plural': 'Team Access Tokens',
            },
        ),
    ]
