# Generated by Django 3.1.3 on 2021-11-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(blank=True, default='', max_length=50000, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Cache',
                'verbose_name_plural': 'Cache',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Is Completed?'),
        ),
        migrations.AddField(
            model_name='team',
            name='data',
            field=models.CharField(blank=True, default='', max_length=10000, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='team',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finish Time'),
        ),
        migrations.AddField(
            model_name='team',
            name='player4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Player 4'),
        ),
        migrations.AddField(
            model_name='team',
            name='player5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Player 5'),
        ),
        migrations.AddField(
            model_name='team',
            name='player6',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Player 6'),
        ),
        migrations.AddField(
            model_name='team',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='player3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Player 3'),
        ),
    ]
