# Generated by Django 3.1.3 on 2021-11-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211103_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
