# Generated by Django 3.1.3 on 2021-12-24 00:26

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cache_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='cache',
            name='game',
            field=models.CharField(blank=True, default='', max_length=50000, verbose_name='game'),
        ),
    ]
